
server:
  port: 8222

spring:
  application:
    name: gateway

  # Optional: connect to config server
#  config:
#    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: school-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  tracing:
    sampling:
      probability: 1.0
